spring.application.name=wasac-utility-billing

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/wasac_billing?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Africa/Kigali
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

# SQL init for triggers and stored procedures
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.sql.init.separator=//
spring.sql.init.schema-locations=classpath:routines.sql

# Gmail SMTP — replace with your credentials
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=usanasenicejosiane@gmail.com
spring.mail.password=qsqs mvfv jprk cory
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# JWT
app.jwt.secret=WasacUtilityBillingSecretKey2026MustBeAtLeast256BitsLongForHS256Algorithm!!
app.jwt.access-token-expiration-ms=3600000
app.jwt.refresh-token-expiration-ms=604800000

# OTP
app.otp.length=6
app.otp.expiration-minutes=10

# Server
server.port=8080

# Application base URL — used in email links
app.base-url=http://localhost:8080

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.disable-swagger-default-url=true

# Logging
logging.level.com.wasac.ne=INFO
logging.level.org.springframework.security=WARN
